language: python

script: 
 - echo "Script Test" 

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "testapplication"
  env: "poll-env"
  bucket_name: "elasticbeanstalk-us-west-2-260847186174"
